// Code generated by goctl. DO NOT EDIT.
package types

type ChangePasswdRequest struct {
	NewPasswd string `json:"newPasswd"`
}

type ChangePasswdResponse struct {
	Message string `json:"message"`
}

type EmailLoginRequest struct {
	Email  string `json:"email"`
	VeCode string `json:"veCode"`
}

type EmailLoginResponse struct {
	UserId       int64  `json:"userId"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type PasswdLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type PasswdLoginResponse struct {
	UserId       int64  `json:"userId"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	VeCode   string `json:"veCode"`
}

type RegisterResponse struct {
	UserId       int64  `json:"userId"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type SendCodeRequest struct {
	Email string `json:"email"`
}

type SendCodeResponse struct {
	Message string `json:"message"`
}

type SignoutRequest struct {
	Email string `json:"email"`
}

type SignoutResponse struct {
	Message string `json:"message"`
}

type UserInfoRequest struct {
	UserId string `json:"userId"`
}

type UserInfoResponse struct {
	UserId int64  `json:"userId"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}
