// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package fileclient

import (
	"context"

	"fileup/rpc/file/file"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = file.Request
	Response = file.Response

	File interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultFile struct {
		cli zrpc.Client
	}
)

func NewFile(cli zrpc.Client) File {
	return &defaultFile{
		cli: cli,
	}
}

func (m *defaultFile) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := file.NewFileClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
